<template>
    <header>
        <nav>
            <ul>
                <li>
                    <button>Shops</button>
                </li>
                <li>
                    <button>Coffee</button>
                </li>
            </ul>
        </nav>
    </header>
</template>